connections:
  - name: mongodb1
    type: MONGO
    connectionStringFromEnv: MONGO_CONN
    metrics:
      - name: active_user_count
        helpString: users in the product
        database: test
        collection: test
        query: '{"is_active":true}'
        time: 10
      - name: total_user_count
        helpString: users in the product
        database: test
        collection: test
        query: ""
        time: 120
      - name: user_balance
        helpString: user balance values
        database: test
        collection: test
        query: '{"name":"alice"}'
        field: "balance"
        mode: "value"
        time: 30
        labels:
          role: "alice"
      - name: user_balance
        helpString: user balance values
        database: test
        collection: test
        query: '{"name":"bob"}'
        field: "balance"
        mode: "value"
        time: 30
        labels:
          role: "bob"
  - name: postgres1
    type: SQL
    connectionStringFromEnv: POSTGRES_CONN
    metrics:
      - name: template_count
        helpString: products in the db
        query: select * from templates
        time: 2
      - name: active_template_count
        helpString: products in the db
        query: error
        time: 4
